# Generated by Django 5.1.6 on 2025-02-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dietplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietPlan',
        ),
    ]
