# Generated by Django 5.1.6 on 2025-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_delete_dietplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField(default=30)),
                ('min_height', models.IntegerField(default=160)),
                ('max_height', models.IntegerField(default=180)),
                ('min_weight', models.IntegerField(default=50)),
                ('max_weight', models.IntegerField(default=80)),
                ('goal', models.CharField(default='general', max_length=20)),
                ('diet_plan', models.TextField(default='')),
                ('image_urls', models.TextField(default='')),
            ],
        ),
    ]
