# Generated by Django 5.1.6 on 2025-02-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_dietplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='calories',
            field=models.IntegerField(default=2000),
        ),
    ]
