# Generated by Django 5.1.6 on 2025-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_dietplan_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='calories',
            field=models.IntegerField(default=5000),
        ),
    ]
